#ifndef __UNIFINGER_VERSION_H__
#define __UNIFINGER_VERSION_H__

#define SFM_SDK_VERSION_INFO
#define SFM_SDK_VERSION_MAJOR 3
#define SFM_SDK_VERSION_MINOR 3
#define SFM_SDK_VERSION_REVISION 0
#define SFM_SDK_FILE_VERSION 3,3,0
#define SFM_SDK_PRODUCT_VERSION 3,3,0
#define SFM_SDK_FILE_VERSION_STR "3.3.0"


#endif
